### PR TITLE
Add support for Storage

### LINKED ISSUE #49: Add support for storage

### PR DESCRIPTION
**Pull request by RenzoTsai**

### CODE REVIEW

**Comment by RenzoTsai** [comment]
I meet a very strange problem now. The Java CI test only fails in windows. And I think the problem may be related to windows' file path because in windows it reports that the app do not load the file correctly. Cause my computer runs on macOS, could some of you help me fix this problem? Thx a lot!

**Comment by RenzoTsai** [comment]
I think I have found the reason and maybe we have to edit the` runtest.bat`. In runtest.bat, this line means our data file will be set in the \build\libs: `java -jar %jarloc% < ..\..\text-ui-test\input.txt > ..\..\text-ui-test\ACTUAL.TXT`, but our data file should be in `data\` or `text-ui-test\`

**Comment by DeetoMok** [comment]
Looks good! Great job!!

**Comment by DeetoMok** [comment]
Maybe is it a good idea to add an interface for our saving classes to implement, as an enhancement to this?

**Comment by DeetoMok** [comment]
After searching online, seems like interface would not work for us here

**Pull request merged**
